### ISSUE TITLE
Compatible with paper_trail (4.0.0.beta1)?

### ISSUE THREAD

**Issue by barrychc** [globalize/globalize-versioning#10]
Hi there,

May I know if the gem is compatible with paper_trail (4.0.0.beta1)? I wanted to update the paper_trail gem to get rid of deprecation warning in Rails 4.2 but encountered the following error. Thanks very much for your attention.

Bundler could not find compatible versions for gem "paper_trail":
  In Gemfile:
    globalize-versioning (~> 0.1.0) ruby depends on
      paper_trail (~> 3.0.0) ruby

    paper_trail (4.0.0.beta1)

**Comment by simi** [comment]
I'll take a look at this. We need to provide paper_trail 4 compatible version with final release.

**Comment by simi** [comment]
@barrychc you can try https://github.com/globalize/globalize-versioning/pull/12 and 4.0.0.beta2. It will be merged soon into master anyway.

**Comment by barrychc** [comment]
Tested #12 OK. Many thanks, @simi.
