### ISSUE TITLE
New release with paper_trail 4 support

### ISSUE THREAD

**Issue by jyrkij** [globalize/globalize-versioning#13]
As stated in #12 support is there but we need a new release in rubygems to use this.

**Comment by iamWh1sp3r** [comment]
Any idea when the paper_trail 4 support will be available trough RubyGems ?

**Comment by bricesanchez** [comment]
:+1:

**Comment by olliebennett** [comment]
Specifying a git URL in the `Gemfile` will resolve for now:

```
gem 'globalize-versioning', git: 'https://github.com/globalize/globalize-versioning.git'
```

Would be great to see it pushed to RubyGems though!

**Comment by simi** [comment]
@olliebennett ahh thanks, I totally forgot about that. It is released now!

https://rubygems.org/gems/globalize-versioning/versions/0.2.0

:confetti_ball:
