### ISSUE TITLE
Undefined method 'locale=' issue

### ISSUE THREAD

**Issue by charlimmelman** [globalize/globalize-versioning#7]
I am having the exact same issue as mentioned here:

https://github.com/globalize/globalize/issues/101

I managed to fix the problem by following the advice, and creating a migration to add 'locale' to the versions table.

Perhaps there is a proper fix, or perhaps I have done something wrong?

**Comment by HenryYan2012** [comment]
I have the same issue.
Any updates?

**Comment by NILID** [comment]
i added locale to call to translates, such as: 

`translates :name, :locale, :versioning => :paper_trail`

and it works
